# This is a basic workflow to help you get started with Actions

name: releaser

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: snickerbockers/submodules-init@v4
      
      - name: Run a multi-line script
        run: |
          rm -rvf .git
          mkdir ../nyanarchiste_I_use_Arch_BTW
          cp -rf * ../nyanarchiste_I_use_Arch_BTW/
          mv ../nyanarchiste_I_use_Arch_BTW .
          cp -rf nyanarchiste_I_use_Arch_BTW nyanarchiste_windows
          wget -q https://github.com/cosmo-ray/yirl/releases/download/latest/yirl.tar.gz
          wget -q https://github.com/cosmo-ray/yirl/releases/download/latest_win/yirl.zip
          mv yirl.tar.gz nyanarchiste_I_use_Arch_BTW
          cd nyanarchiste_I_use_Arch_BTW
          tar -xf yirl.tar.gz
          rm yirl.tar.gz
          echo nyanarchiste_I_use_Arch_BTW
          echo '#!/bin/bash' > nyanarchiste.sh
          chmod +x nyanarchiste.sh
          echo yirl/yirl-loader.sh -d ./ -n Nyanarchiste -P yirl/ > nyanarchiste.sh
          cd ..
          mv yirl.zip nyanarchiste_windows
          cd nyanarchiste_windows
          mkdir tmp
          mv yirl.zip tmp
          cd tmp
          unzip yirl.zip
          cd ..
          mv tmp/* .
          rm -rvf tmp
          mv yirl-loader.exe Nyanarchiste.exe
          # it seems sazanami is out on windows, so no japanese for its users.
          rm sazanami-mincho.ttf
          cp DejaVuSansMono.ttf sazanami-mincho.ttf
          rm yirl.zip
          cd ..
          tar cfz  nyanarchiste_I_use_Arch_BTW.tar.gz ./nyanarchiste_I_use_Arch_BTW/
          zip -r nyanarchiste_windows.zip ./nyanarchiste_windows/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            nyanarchiste_I_use_Arch_BTW.tar.gz
            nyanarchiste_windows.zip
